app = "shmuel-tech-blog"
primary_region = "ams"
kill_signal = "SIGINT"

[build]
  dockerfile = "Dockerfile"

[env]
  SERVICE_NAME = "blog"
  PORT = "80"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  
  [[http_service.checks]]
    path = "/health"
    method = "GET"
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
