version: '3.9'
services:
  traefik:
    image: traefik:v2.11
    ports:
    - 80:80
    - 8080:8080
    command:
    - --providers.docker=true
    - --entrypoints.web.address=:80
    - --api.insecure=true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  main-site:
    build: ./services/main-site
    environment:
    - SERVICE_NAME=main-site
    labels:
    - traefik.enable=true
    - traefik.http.routers.main-site.rule=Host(`shmuel.localhost`)
    - traefik.http.services.main-site.loadbalancer.server.port=80
    depends_on:
    - traefik
  media:
    build: ./services/media
    environment:
    - SERVICE_NAME=media
    labels:
    - traefik.enable=true
    - traefik.http.routers.media.rule=Host(`media.localhost`)
    - traefik.http.services.media.loadbalancer.server.port=80
    depends_on:
    - traefik
  dns-proxy:
    build: ./services/dns-proxy
    environment:
    - SERVICE_NAME=dns-proxy
    labels:
    - traefik.enable=true
    - traefik.http.routers.dns-proxy.rule=Host(`dns-proxy.localhost`)
    - traefik.http.services.dns-proxy.loadbalancer.server.port=80
    depends_on:
    - traefik
  test-service:
    build: ./services/test-service
    environment:
    - SERVICE_NAME=test-service
    labels:
    - traefik.enable=true
    - traefik.http.routers.test-service.rule=Host(`test-service.localhost`)
    - traefik.http.services.test-service.loadbalancer.server.port=80
    depends_on:
    - traefik
