site_name: Shmuel Tech Documentation
site_description: Documentation for the shmuel-tech monorepo
site_author: Shmuel Tech
site_url: https://shmueltech.github.io/shmuel-tech/

repo_name: shmueltech/shmuel-tech
repo_url: https://github.com/shmueltech/shmuel-tech

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - git-revision-date-localized

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Development: getting-started/development.md
    - Deployment: getting-started/deployment.md
  - Services:
    - Overview: services/overview.md
    - Creating Services: services/creating-services.md
  - Architecture:
    - System Design: architecture/system-design.md
    - Local Development: architecture/local-development.md
    - Production: architecture/production.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true 